services:
  calviewserver:
    image: dubhar/calviewserver:latest
    expose:
      - 5000
    environment:
      CALENDAR_URL: "https://wolke.jefrickel.de/remote.php/dav/"
      CALENDAR_USER: "myUser"
      CALENDAR_TOKEN: "myAppToken"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
  calviewclient:
    image: dubhar/calviewclient:latest
    ports:
      - "8080:3000"
    environment:
      CALENDAR_URL: "calviewserver:5000"
