name: build and push docker

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the server image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/calviewserver:latest
            ${{ secrets.DOCKERHUB_USER }}/calviewserver:${{github.ref_name}}
      - name: Build and push the client image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/calviewclient:latest
            ${{ secrets.DOCKERHUB_USER }}/calviewclient:${{github.ref_name}}
